# Generated by Django 2.2 on 2020-01-10 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forex_app', '0002_forex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forex',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_app_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='binary_accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=50)),
                ('payment', models.IntegerField(default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
