# Generated by Django 2.2 on 2020-01-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_app', '0005_binarysignals_forexsignals'),
    ]

    operations = [
        migrations.AddField(
            model_name='binary_accounts',
            name='paid_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forex',
            name='paid_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
