# Generated by Django 2.2 on 2020-01-27 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forex_app', '0007_auto_20200127_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='binarysignals',
            name='starttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
