# Generated by Django 2.2 on 2020-02-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_app', '0008_binarysignals_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='binary_accounts',
            name='paid_on',
            field=models.DateTimeField(default='2020-2-10'),
        ),
    ]
