# Generated by Django 2.2 on 2020-02-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_app', '0009_binary_accounts_paid_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binary_accounts',
            name='paid_on',
            field=models.DateTimeField(default='1111-1-1'),
        ),
    ]
