# Generated by Django 2.2 on 2020-02-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_app', '0011_auto_20200204_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binary_accounts',
            name='paid_on',
            field=models.DateField(default='2020-2-10'),
        ),
    ]
