# Generated by Django 2.2 on 2020-02-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_app', '0013_auto_20200204_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binary_accounts',
            name='paid_on',
            field=models.DateTimeField(),
        ),
    ]
