# Generated by Django 2.2 on 2020-02-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_app', '0016_binary_accounts_paid_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='forex',
            name='paid_on',
            field=models.DateTimeField(default='2020-2-10'),
        ),
    ]
